# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
    - master

pool:
    vmImage: ubuntu-latest

variables:
    - ${{ if eq(variables['build.sourceBranchName'], 'master') }}:
          - template: Deploy/Variables/vars-prd.yml
    - ${{ if eq(variables['build.sourceBranchName'], 'develop') }}:
          - template: Deploy/Variables/vars-dev.yml

steps:
    - checkout: self
      persistCredentials: true

    - script: dotnet build --configuration $(buildConfiguration)
      displayName: 'dotnet build $(buildConfiguration)'

    - script: |
          git config --global user.email "alexandre@example.com"
          git config --global user.name "alexandre"
          git tag -a tagName -m '$(tagMessage)'
          git push --tags
      displayName: git tag
